moderator/urls.py
from django.urls import path 
from . import views
from django.conf.urls.static import static
from tweetwave.settings import MEDIA_ROOT, MEDIA_URL

app_name = 'moderator' 

urlpatterns = [
    path('', views.index, name='index'),
    path('approve/<str:uuid>/', views.approve, name='approve'),
    path('remove/<str:uuid>/', views.remove, name='remove'),
    path('approved/', views.approved, name='approved'),
    path('pending/', views.pending, name='pending'),
    path('flagged/', views.flagged, name='flagged'),
    path('adverts/', views.adverts, name='adverts'),
    path('contact/<str:uuid>', views.contact, name='contact'),
    path('reject/<str:uuid>', views.reject, name='reject'),
] + static(MEDIA_URL, document_root=MEDIA_ROOT)

submission/urls.py
from django.urls import path 
from . import views
from django.conf.urls.static import static 
from tweetwave.settings import MEDIA_ROOT, MEDIA_URL

app_name = 'submission'

urlpatterns = [
    path('', views.index, name='index'),
    path('confession/', views.saved, name='saved'),
    path('advertising/', views.advertising, name='advertising'),
    path('business/', views.business, name='business'),
    path('about/', views.about, name='about'),
]  + static(MEDIA_URL, document_root=MEDIA_ROOT)

tweetwave/urls.py
from django.contrib import admin
from django.urls import path, include
import submission, moderator, users

urlpatterns = [
    path('admin/', admin.site.urls),
    path('mod/', include('moderator.urls')),
    path('', include('submission.urls')),
    path('users/', include('users.urls')),
]

users/urls.py
from django.urls import path, include
from . import views
from django.conf.urls.static import static 
from tweetwave.settings import MEDIA_ROOT, MEDIA_URL

app_name = 'users'

urlpatterns = [
    path('signin/', views.signin, name='signin'),
    path('signout/', views.signout, name='signout'),
]  + static(MEDIA_URL, document_root=MEDIA_ROOT)

moderator/models.py
from django.db import models
from uuid import uuid4

class Advert(models.Model):
    uuid = models.UUIDField(default=uuid4)
    name = models.CharField(max_length=255)
    email = models.EmailField()
    company = models.CharField(max_length=255)
    description = models.TextField()

    def __str__(self):
        return self.name

submission/models.py
from django.db import models
from uuid import uuid4

class Confession(models.Model):
    uuidField = models.UUIDField(default=uuid4)
    approved = models.BooleanField(default=False)
    text = models.TextField()
    flag = models.BooleanField(default=False)
    media = models.FileField(upload_to="mediaFiles", null=True, blank=True)

    def __str__(self):
        if len(list(self.text)) > 50:
            return f'{self.text[0:50]}...'
        else: 
            return self.text

users/models.py
from django.db import models

# Create your models here.

moderator/views.py
from django.shortcuts import render, redirect
from submission.models import Confession
from moderator.models import Advert
from django.contrib.auth.decorators import login_required
import smtplib

def countFlags():
    flags = Confession.objects.all().filter(flag=True)
    return len(flags)

@login_required()
def index(request):
    confessions = Confession.objects.all()
    context = {'confessions': confessions, 'number': countFlags()}
    return render(request, 'moderator/index.html', context)

@login_required()
def approve(request, uuid):
    confession = Confession.objects.get(uuidField=uuid)
    confession.approved = True
    confession.save()
    return redirect('moderator:index')

@login_required()
def remove(request, uuid):
    confession = Confession.objects.get(uuidField=uuid)
    confession.delete()
    return redirect('moderator:index')

@login_required()
def approved(request):
    confessions = Confession.objects.all().filter(approved=True)
    context = {'confessions': confessions, 'number': countFlags()}
    return render(request, 'moderator/approved.html', context)


@login_required()
def pending(request):
    confessions = Confession.objects.all().filter(approved=False)
    context = {'confessions': confessions, 'number': countFlags()}
    return render(request, 'moderator/pending.html', context)

@login_required()
def flagged(request):
    flags = Confession.objects.all().filter(flag=True)
    number = len(flags)
    context = {'flags': flags, 'number': number}
    return render(request, 'moderator/flagged.html', context)

@login_required()
def adverts(request):
    adverts = Advert.objects.all()
    context = {'adverts': adverts, 'number': countFlags()}
    return render(request, 'moderator/adverts.html', context)

@login_required()
def contact(request, uuid):
    advert = Advert.objects.get(uuid=uuid)
    sender = "edgarmatthew247@gmail.com"
    receipient = advert.email
    subject = "Advertising with TweetWave"
    body = f"""Dear {advert.name}, <br> We are pleased to accept your request to advertise with our company. We believe that our p <br> latform will be a great fit for your business, and we are excited to help you reach your marketing goals. <br> To get started, please provide us with the following information: <br> A brief description of your business and the products or services you offer <br> The type of ad you would like to run (e.g. banner ad, sponsored post, etc.) <br> The target audience for your ad (e.g. age, gender, location, etc.) <br> The desired start and end dates for your ad campaign <br> Once we have this information, we will create a customized advertising plan for your business and provide you  <br> with a detailed proposal. We look forward to working with you and helping you achieve success with your advertising efforts. <br> Sincerely, <br> Admin - TweetWave"""
    server = smtplib.SMTP("smtp.gmail.com", 587)
    server.sendmail(sender, receipient, subject, body)


@login_required()
def reject(request, uuid):
    advert = Advert.objects.get(uuid=uuid)
    advert.delete()
    return redirect('moderator:adverts')

submission/views.py
from django.shortcuts import render, redirect
from .models import Confession
from moderator.models import Advert

def index(request):
    context = {}
    return render(request, 'submission/index.html', context)

def saved(request):
    if request.method == 'POST':
        tweet = request.POST['tweet']
        try:
            media = request.FILES['attachment']
        except:
            media = None
        newTweet = Confession(text=tweet, media=media)
        newTweet.save()
        return redirect('submission:index')

def advertising(request):
    if request.method == 'POST':
        name = request.POST['name']
        email = request.POST['email']
        company = request.POST['company']
        message = request.POST['message']
        newConfession = Advert(name=name, email=email, company=company, description=message)
        newConfession.save()
        return redirect('submission:index')
    context = {}
    return render(request, 'submission/advertising.html', context)

def business(request):
    context = {}
    return render(request, 'submission/business.html', context)

def about(request):
    context = {}
    return render(request, 'submission/about.html', context)

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout, authenticate 
from django.contrib import messages

def signin(request):
    if request.method == 'POST':
        username = request.POST['username']
        pass1 = request.POST['password']
        user = authenticate(username=username, password=pass1)

        if user is not None:
            login(request, user)
            return redirect('moderator:index')
        else:
            messages.error(request, 'Invalid username or password')
            return redirect('moderator:index')

    return render(request, 'registration/login.html')

def signout(request):
    logout(request)
    messages.success(request, 'You have been logged out')
    return redirect('submission:index')

moderator/templates/moderator/adverts.html
{% extends 'moderator/base.html' %}

{% block content %}
    {% for advert in adverts %}
        <div class="card mb-3">
            <div class="card-body">
              <h5 class="card-title">{{ advert.name }}</h5>
              <h6 class="card-subtitle mb-2 text-muted">{{ advert.company }}</h6>
              <p class="card-text">{{ advert.description }}</p>
              <!-- <a href="{% url 'moderator:contact' advert.uuid %}" class="btn btn-success btn-sm">Accept</a> -->
              <a href="#" class="btn btn-success btn-sm">Accept</a>
              <a href="{% url 'moderator:reject' advert.uuid %}" class="btn btn-danger btn-sm">Reject</a>
            </div>
        </div>     
    {% empty %}
        <h3>No pending business requests</h3>
    {% endfor %}
{% endblock content %}

moderator/templates/moderator/approved.html
{% extends 'moderator/base.html' %}

{% block content %}
{% for confession in confessions %}
{% if confession.media %}
<div class="card p-1 m-1">
    <div class="card-body">
        <div class="row">
            <div class="col-1">
                <img src="{{ confession.media.url }}" alt="My Image" width="100" height="100" class="img-thumbnail"
                    id="thumbnail">
                <script>
                    var img = document.getElementById("thumbnail");
                    img.onclick = function () {
                        img.style.width = "500px";
                        img.style.height = "500px";
                        img.style.position = "fixed";
                        img.style.top = "50%";
                        img.style.left = "50%";
                        img.style.transform = "translate(-50%, -50%)";
                    }
                    document.onclick = function (event) {
                        if (event.target != img) {
                            img.style = "";
                        }
                    }
                </script>
            </div>
            <div class="col-11">
                {{ confession.text | linebreaks }}
                <div class="button-group btn-group">
                    <form action="{% url 'moderator:remove' confession.uuidField %}" method="POST" class="mx-2">
                        {% csrf_token %}
                        <button name="submit" class="btn btn-danger btn-sm">Delete</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% else %}
<div class="card p-1 m-1">
    <p>
    <div class="card-body">
        {{ confession.text | linebreaks }}
        <div class="button-group btn-group">
            <form action="{% url 'moderator:remove' confession.uuidField %}" method="POST" class="mx-2">
                {% csrf_token %}
                <button name="submit" class="btn btn-danger btn-sm">Delete</button>
            </form>
        </div>
    </div>
    </p>
</div>
{% endif %}
{% empty %}
<p>No pending confessions</p>
{% endfor %}
{% endblock content %}

moderator/templates/moderator/base.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
    <title>
        TweetWave - Admin
    </title>
    <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
        integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css"
        integrity="sha512-+4zCK9k+qNFUR5X+cKL9EIR+ZOhtIloNl9GIKS57V1MyNsYpYcUrUeQc9vNfzsWfV28IaLL3i96P9sdNyeRssA=="
        crossorigin="anonymous" /> -->
    <link href="https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.css" rel="stylesheet">
    <script src="https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.js"></script>
    <link rel="icon" href="{% static 'moderator/img/tweetwave.ico' %}">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0 shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'moderator/css/base.css' %}">
    <link rel="stylesheet" href="{% static '../static/css/output.css' %}">
    <script src="{% static '../static/js/menu.js' %}"></script>
</head>

<body>
    <div id="container">
        <div class="sidebar">
            <h2>
                <a href="{% url 'submission:index' %}">TweetWave</a>
            </h2>
            <ul class="list-unstyled mt-4">
                <li class="mb-3"><a href="{% url 'moderator:index' %}" class="text-white"><i
                            class="fas fa-home fa-lg mr-2"></i>Home</a></li>
                <li class="mb-3"><a href="{% url 'moderator:pending' %}" class="text-white"><i
                            class="fas fa-hourglass fa-lg mr-2"></i>Pending</a></li>
                <li class="mb-4"><a href="{% url 'moderator:approved' %}" class="text-white"><i
                            class="fas fa-check-circle fa-lg mr-2"></i>Approved</a></li>
                <li class="mb-4 pt-3">
                    <a href="{% url 'moderator:flagged' %}" class="text-white d-inline"><i
                            class="fas fa-flag fa-lg mr-2"></i>Flagged
                        <span class="badge badge-secondary counter badge-pill d-inline">{{ number }}</span>
                    </a>
                </li>
                <li class="mb-4 pt-3"><a href="{% url 'moderator:adverts' %}" class="text-white"><i
                    class="fas fa-tags fa-lg mr-2"></i>Adverts</a></li>
                <li><a href="{% url 'users:signout' %}" class="text-white"><i
                            class="fas fa-window-close fa-lg mr-2"></i>Log Out</a></li>               
            </ul>
        </div>
        <div id="main">
                {% block content %}
                {% endblock content %}
        </div>
        <footer class="p-3 fixed-bottom container footer">
            <p>Copyright 2022 TweetWave</p>
        </footer>
    </div>
</body>
</html>

moderator/templates/moderator/flagged.html
{% extends 'moderator/base.html' %}

{% block content %} 
    {% for flag in flags %}
            {% if flag.media %}
                <div class="card p-1 m-1">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-1">
                                <img src="{{ flag.media.url }}" alt="My Image" width="100" height="100" class="img-thumbnail" id="thumbnail">
                                <script>
                                    var img = document.getElementById("thumbnail");
                                    img.onclick = function() {
                                    img.style.width = "500px";
                                    img.style.height = "500px";
                                    img.style.position = "fixed";
                                    img.style.top = "50%";
                                    img.style.left = "50%";
                                    img.style.transform = "translate(-50%, -50%)";
                                    }
                                    document.onclick = function(event) {
                                    if (event.target != img) {
                                        img.style = "";
                                    }
                                    }
                                </script>
                            </div>
                            <div class="col-11">
                                {{ flag.text | linebreaks }}
                                <div class="button-group btn-group">
                                    <form action="{% url 'moderator:remove' flag.uuidField %}" method="POST" class="mx-2">
                                        {% csrf_token %}
                                        <button name="submit" class="btn btn-danger btn-sm">Delete</button>
                                    </form>
                                    <form action="{% url 'moderator:approve' confession.uuidField %}" method="POST" class="mx-2">
                                        {% csrf_token %}
                                        <button name="submit" class="btn btn-primary btn-sm">Approve</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>               
            {% else %}
                <div class="card p-1 m-1">
                    <p>
                        <div class="card-body">
                            {{ flag.text | linebreaks }}
                            <div class="button-group btn-group">
                                <form action="{% url 'moderator:remove' flag.uuidField %}" method="POST" class="mx-2">
                                    {% csrf_token %}
                                    <button name="submit" class="btn btn-danger btn-sm">Delete</button>
                                </form>
                                <form action="{% url 'moderator:approve' flag.uuidField %}" method="POST" class="mx-2">
                                    {% csrf_token %}
                                    <button name="submit" class="btn btn-primary btn-sm">Approve</button>
                                </form>
                            </div>
                        </div>
                    </p>
                </div>
            {% endif %}
    {% empty %}
        <p>No flagged confessions</p>
    {% endfor %}
{% endblock content %}

moderator/templates/moderator/index.html
{% extends "moderator/base.html" %}

{% block content%}
    <h1>Welcome to TweetWave!</h1>

    <p>TweetWave is a platform where users can anonymously submit confessions to be tweeted. As the
        administrator of this page, you can review and approve confessions before they are tweeted.</p>

    <h2>How to Use TweetWave</h2>

    <ol>
        <li>Users visit the TweetWave website and submit a confession using the form on the page.</li>
        <li>The confession is sent to your admin dashboard, where you can review and approve it.</li>
        <li>Once you have approved a confession, it will be tweeted from the TweetWave Twitter account.
        </li>
    </ol>

    <h2>Tips for Using TweetWave</h2>

    <ul>
        <li>Moderate confessions carefully to ensure that they are appropriate and in line with your guidelines.
        </li>
        <li>Encourage users to submit confessions by promoting the website on social media and other platforms.
        </li>
        <li>Use the analytics on your admin dashboard to track the performance of your tweets and see which
            confessions are most popular.</li>
    </ul>

    <h2>Contact Us</h2>

    <p>If you have any questions or need help using TweetWave, please contact us at
        support@confessiontweeter.com. We're here to help you make the most of this platform!</p>
{% endblock content%}

moderator/templates/moderator/pending.html
{% extends 'moderator/base.html' %}

{% block content %}
    {% for confession in confessions %}
            {% if confession.media %}
                <div class="card p-1 m-1">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-1">
                                <img src="{{ confession.media.url }}" alt="My Image" width="100" height="100" class="img-thumbnail" id="thumbnail">
                                <script>
                                    var img = document.getElementById("thumbnail");
                                    img.onclick = function() {
                                    img.style.width = "500px";
                                    img.style.height = "500px";
                                    img.style.position = "fixed";
                                    img.style.top = "50%";
                                    img.style.left = "50%";
                                    img.style.transform = "translate(-50%, -50%)";
                                    }
                                    document.onclick = function(event) {
                                    if (event.target != img) {
                                        img.style = "";
                                    }
                                    }
                                </script>
                            </div>
                            <div class="col-11">
                                {{ confession.text | linebreaks }}
                                <div class="button-group btn-group">
                                    <form action="{% url 'moderator:remove' confession.uuidField %}" method="POST" class="mx-2">
                                        {% csrf_token %}
                                        <button name="submit" class="btn btn-danger btn-sm">Delete</button>
                                    </form>
                                    <form action="{% url 'moderator:approve' confession.uuidField %}" method="POST" class="mx-2">
                                        {% csrf_token %}
                                        <button name="submit" class="btn btn-primary btn-sm">Approve</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>               
            {% else %}
                <div class="card p-1 m-1">
                    <p>
                        <div class="card-body">
                            {{ confession.text | linebreaks }}
                            <div class="button-group btn-group">
                                <form action="{% url 'moderator:remove' confession.uuidField %}" method="POST" class="mx-2">
                                    {% csrf_token %}
                                    <button name="submit" class="btn btn-danger btn-sm">Delete</button>
                                </form>
                                <form action="{% url 'moderator:approve' confession.uuidField %}" method="POST" class="mx-2">
                                    {% csrf_token %}
                                    <button name="submit" class="btn btn-primary btn-sm">Approve</button>
                                </form>
                            </div>
                        </div>
                    </p>
                </div>
            {% endif %}
    {% empty %}
        <p>No pending confessions</p>
    {% endfor %}
{% endblock content %}

submission/templates/submission/about.html
{% extends 'submission/base.html' %}

{% block content %}
<div class="container">
    <div class="row mt-5">
        <div class="col-md-12">
            <h1>About Tweetwave</h1>
            <hr>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <p>Tweetwave is a platform where users can submit their confessions, and they will be automatically tweeted
                to our account. This allows users to anonymously share their thoughts and feelings with the world.</p>
            <p>To submit a confession, simply fill out the form on the homepage and click submit. Your confession will
                be tweeted out shortly after, with no information identifying you.</p>
        </div>
    </div>
</div>
{% endblock content %}

submission/templates/submission/advertising.html
{% extends "submission/base.html" %}

{% block content%}
    <div class="container">
        <h1 class="text-center mt-5">Tweetwave Advertising</h1>
        <p class="lead text-center mb-5">Are you interested in advertising your business on Tweetwave? Here's what you
            need to know.</p>
            <hr>
        <div class="row">
            <div class="col-md-6">
                <h3>Reach a Large Audience</h3>
                <p>With thousands of users tweeting confessions on Tweetwave every day, your ad will be seen by a wide
                    range of people. Whether you're looking to promote a new product, a sale, or just raise awareness
                    about your brand, Tweetwave can help you reach your target audience.</p>
            </div>
            <div class="col-md-6">
                <h3>Affordable and Flexible</h3>
                <p>Our advertising options are affordable and flexible, so you can choose the right plan for your
                    business. You can target your ads by location, interests, and more, and you can easily track the
                    performance of your ads to see how well they're doing.</p>
            </div>
        </div>
        <div class="row mt-5">
            <div class="col-md-12">
                <h4>To advertise with us, please fill out the form below and we shall get in touch with you as soon as we can</h4>
                <br>
                <form method="POST" action="{% url 'submission:advertising' %}">
                    {% csrf_token %}
                    <div class="form-group mb-3">
                    <label for="name">Name:</label>
                    <input type="text" class="form-control" id="name" name="name" placeholder="Enter your name">
                    </div>
                    <div class="form-group mb-3">
                    <label for="email">Email address:</label>
                    <input type="email" class="form-control" id="email" name="email" placeholder="Enter your email">
                    </div>
                    <div class="form-group mb-3">
                    <label for="company">Company (Optional):</label>
                    <input type="text" class="form-control" id="company" name="company" placeholder="Enter your company name">
                    </div>
                    <div class="form-group mb-3">
                    <label for="message">Description:</label>
                    <textarea class="form-control" id="message" name="message" rows="3" placeholder="Enter a short description about your requirements"></textarea>
                    </div>
                    <button type="submit" class="btn btn-primary float-right mb-3">Submit</button>
                </form>
            </div>
        </div>
    </div>
{% endblock content%}

{% block footer%}
{% endblock footer%}

submission/templates/submission/base.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css"
    integrity="sha512-+4zCK9k+qNFUR5X+cKL9EIR+ZOhtIloNl9GIKS57V1MyNsYpYcUrUeQc9vNfzsWfV28IaLL3i96P9sdNyeRssA=="
    crossorigin="anonymous" />
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
    integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous"> -->
  <link href="https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.css" rel="stylesheet">
  <script src="https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.js"></script>
  <link rel="stylesheet" href="{% static 'submission/css/base.css' %}">
  <link rel="icon" href="{% static 'submission/img/tweetwave.ico' %}">
  <link rel="stylesheet" href="{% static '../static/css/output.css' %}">
  <script src="{% static '../static/js/menu.js' %}"></script>
  {% block style %}
  {% endblock style %}
  <title>TweetWave</title>
</head>

<body>
  <nav class="navbar navbar-expand navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'submission:index' %}">
      <img src="{% static 'submission/img/tweetwave.ico' %}" alt="Logo" style="width:40px;">
    </a>
    <a class="navbar-brand" href="{% url 'submission:index' %}">Tweetwave</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
      aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'submission:advertising' %}">Advertising <span
              class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'submission:business' %}">Business</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'submission:about' %}">About</a>
        </li>
      </ul>
    </div>
  </nav>
  {% block content %}
  {% endblock content %}
  {% block footer %}

  <footer class="p-3 fixed-bottom container-fluid bg-dark">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <ul class="list-inline">
            <li class="list-inline-item mx-5">
              <a href="#">
                <img src="{% static 'submission/img/facebook.png' %}" alt="Facebook" style="width:20px;">
                Facebook
              </a>
            </li>
            <li class="list-inline-item mx-5">
              <a href="#">
                <img src="{% static 'submission/img/twitter.png' %}" alt="Twitter" style="width:20px;">
                Twitter
              </a>
            </li>
            <li class="list-inline-item mx-5">
              <a href="#">
                <img src="{% static 'submission/img/instagram.png' %}" alt="Instagram" style="width:20px;">
                Instagram
              </a>
            </li>
            <li class="list-inline-item mx-5">
              <a href="#">
                <img src="{% static 'submission/img/github.png' %}" alt="Github" style="width:20px;">
                Github
              </a>
            </li>
            <li class="list-inline-item mx-5 float-right" style="color: white">
              Copyright 2022
              <a href="{% url 'moderator:index' %}">TweetWave</a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </footer>
  {% endblock footer %}
</body>

</html>

submission/templates/submission/business.html
{% extends 'submission/base.html' %}

submission/templates/submission/index.html
{% extends "submission/base.html" %}

{% block content %}
<main role="main" id="main" class="bg-red-500">
  <h1 class="text-3xl font-bold underline">
    <a href="{% url 'submission:index' %}">
      TweetWave
    </a>
  </h1>
  <form class="form p-1" action="{% url 'submission:saved' %}" style="width: 700px" method="POST"
    enctype="multipart/form-data">
    {% csrf_token %}
    <div class="row">
      <!-- <div class="col-10"> -->
      <!-- <input type="text" id="tweet" class="form-control" name="tweet" placeholder="Enter your submission"> -->
      <textarea name="tweet" id="tweet" cols="30" rows="10" placeholder="Enter your submission"></textarea>
      <!-- </div> -->
      <!-- <div class="col-2"> -->
      <input type="file" id="attachment" name="attachment" class="fas fa-paperclip fa-lg">
      <!-- </div> -->
      <input type="submit" value="Submit" class="btn btn-secondary mt-3 mx-auto"">
      </div>
    </form>
  </main>
{% endblock content %}